greenworks/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/login')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('sales/', include('sales.urls')),
    path('expenses/', include('expenses.urls')),

    # path('manager/', include('manager.urls')),
    path('weather/', include('weather.urls')),


]

sales/urls.py
from django.urls import path
from django.contrib import admin
from sales.views import SalesCreateView, SalesDetailView, SalesListView, SalesUpdateView, SalesValidate, SalesDeleteView

urlpatterns = [
    path('', SalesListView.as_view(), name='sales_list'),
    path('create', SalesCreateView.as_view(), name='sales_create'),
    path('<int:pk>/', SalesDetailView.as_view(), name='sales_details'),

    path('<int:pk>/delete', SalesDeleteView.as_view(), name='sales_delete'),
    path('<int:pk>/edit', SalesUpdateView.as_view(), name='sales_update'),
    path('<int:pk>/validate', SalesValidate.as_view(), name='sales_validate'),
]

expenses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse


class Expenses(models.Model):
    EXPENSE_TYPES = [
        ('OTHER', 'Other'),
        ('TRAVEL', 'Travelling'),
        ('WAGES', 'Labour and wages'),
        ('FOOD', 'Food and drinks'),
        ('FUEL', 'Fuel'),
        ('MARKETING', 'Marketing'),
        ('INPUTS', 'Farm Inputs (Fertilizer, pesticides e.t.c'),
    ]

    VALIDATION = [
        ('YES', 'Yes'),
        ('NO', 'No'),
    ]

    name = models.CharField('Expense Name', max_length=100)
    type = models.CharField('Category', max_length=100, choices=EXPENSE_TYPES, default='OTHER')
    when = models.DateField('Date of expenditure')
    description = models.TextField('Describe how you spent the funds')
    amount = models.FloatField('Amount (in KES)')
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None, verbose_name='Recorded By')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    valid = models.CharField('Is Valid?', max_length=100, choices=VALIDATION, default='NO')


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = ('Expense')
        verbose_name_plural = ('Expenses')
        ordering = ['-when']

    def amount_formatted(self):
        return 'Ksh ' + str(self.amount)

    def get_absolute_url(self):
        return reverse('expenses_details', args=[self.id])

templates/dashboard.html
{% extends "layout/master.html" %}

{% block title %}
    Dashboard
{% endblock title %}

{% block content %}
    <div class="col-12">
        <h3 class="text-muted mb-4">Quick Actions</h3>
        <div class="row mb-3">
            <div class="col-6 col-lg-3">
                {% include 'component/action.html' with label="Expenses" route="expenses_list" icon="money-bill" %}
            </div>
            <div class="col-6 col-lg-3">
                {% include 'component/action.html' with label="Sales" route="sales_list" icon="shopping-bag" %}
            </div>
        </div>
    </div>

    {# Latest weather #}
    <div class="col-12">
        <a href="{% url 'weather_list' %}" class="btn btn-outline-primary btn-sm float-end">
            More <i class="fa fa-arrow-right fa-fw"></i>
        </a>
        <h3 class="text-muted mb-4">Latest Weather</h3>
    </div>
    <div class="row">
        {# Weather description #}
        <div class="col-6 col-lg-3">
            {% include 'component/widget.html' with label='Current Weather' value=current_weather.description %}
        </div>

        {# 12 hour precipitation #}
        <div class="col-6 col-lg-3">
            {% include 'component/widget.html' with label='Rain' value=current_weather.precipitation_12_hr_formatted %}
        </div>

        {# Temperature #}
        <div class="col-6 col-lg-3">
            {% include 'component/widget.html' with label='Temperature' value=current_weather.temperature_formatted %}
        </div>

        {# Relative humidity #}
        <div class="col-6 col-lg-3">
            {% include 'component/widget.html' with label='Relative Humidity' value=current_weather.relative_humidity_formatted %}
        </div>
    </div>

    {# Financials #}
    <h3 class="text-muted mb-4">Financials</h3>
    <div class="row">
        {# Sales this month #}
        <div class="col-6 col-lg-3">
            {% include 'component/statistic.html' with label='Sales This Month' value=sales_this_month %}
        </div>

        {# Total sales #}
        <div class="col-6 col-lg-3">
            {% include 'component/statistic.html' with label='Total Sales' value=total_sales %}
        </div>

        {# Month expenses #}
        <div class="col-6 col-lg-3">
            {% include 'component/statistic.html' with label='Expenses This Month' value=expenses_this_month %}
        </div>

        {# Total Expenses #}
        <div class="col-6 col-lg-3">
            {% include 'component/statistic.html' with label='Total Expenses' value=total_expenses %}
        </div>
    </div>

    {% comment %} {# Rainfall trends #}
    <h1 class="text-muted mb-4">Rainfall Trends</h1>

    {# Temperature trends #}
    <h1 class="text-muted mb-4">Temperature Trends</h1>

    {# RH trends #}
    <h1 class="text-muted mb-4">Humidity Trends</h1> {% endcomment %}


{% endblock content %}